describe('Verify that the Batch Management page loads & Batch Template create successfully.', () =>{
    beforeEach('TC_Login: Verify Login to the system with valid credentials.', () => {
        cy.session('login', () =>{
            cy.viewport(1440,900)
            cy.clearCookies()
            cy.clearLocalStorage()
            loginObj.loginURL('/login')
            cy.wait(2000)
            loginObj.enterEmail(loginData.email)
            loginObj.enterPassword(loginData.password)
            loginObj.clickOnLoginBtn()
            cy.log('User logged in successfully')
            cy.wait(2000)
        })
    })

    it('TC_BATCH_01: Verify that the user is able to perform searches using keywords in the Batch module.', ()=>{
        cy.viewport(1440,900)
        loginObj.loginURL('/batch-management')
        cy.wait(3000)
        batchObj.clickOnbatchManagement()
        batchObj.clickOnSearchMenu()
        batchObj.clickOnSearchByBatchName(batchManagementData.batchName)
        batchObj.setSearchByCreatedPerson(batchManagementData.createdPerson)
        batchObj.setSearchByUID(batchManagementData.uid)
        batchObj.setSearchByVerificationUrl(batchManagementData.verificationUrl)
        batchObj.setSearchBySerial(batchManagementData.serial)
        batchObj.clickOnAppyBtn()
        cy.wait(2000)
  
    })

    it('TC_BATCH_TEMP_02: Verify that as a user create a new Batch Template.', () =>{
        cy.viewport(1440,900)
        loginObj.loginURL('/batch-management')
        cy.wait(3000)
        batchObj.clickOnbatchManagement()
        batchObj.clickOnBatchTemplate()
        batchObj.clickOnCreateNewTemplate()
        batchObj.verifyBatchTemplatePage()
        batchObj.setTemplateName(batchManagementData.createdTempName)
        batchObj.clickOnPWATemplateByName(batchManagementData.assignPWAname)
        batchObj.clickOnCreateBtn()
        batchObj.clickOnSubmitCreateBtn()
        batchObj.verifyBatchTemplate()
        // batchObj.clickOnSearchMenu()
        // batchObj.clickOnBatchTemplateResetBtn()
    })

    it('TC_BATCH_TEMP_03: Verify that as a user search Batch Template.', () =>{
        cy.viewport(1440,900)
        loginObj.loginURL('/batch-management')
        cy.wait(3000)
        batchObj.clickOnbatchManagement() 
        batchObj.clickOnBatchTemplate()
        cy.wait(1000)
        batchObj.clickOnBatchTemplateFilterMenu1()
        cy.wait(1000)
        batchObj.batchTemplateNameForSearch(batchManagementData.searchTemplateName)
        batchObj.createdPersonForSearch(batchManagementData.searchCreatedPerson)
        batchObj.clickOnApplyButton()
        cy.wait(2000)
    })

    it('TC_BATCH_04: Verify that as a user create a new Batch.', () =>{
        cy.viewport(1500,1000)
        loginObj.loginURL('/batch-management')
        cy.wait(3000)
        batchObj.clickOnbatchManagement()
        batchObj.verifyBatchManagement()
        batchObj.clickOnNewBatch()
        batchObj.verifyNewBatch()
        batchObj.setBatchName(batchManagementData.createBatchName)
        cy.wait(1000)
        batchObj.setBatchQuantity(batchManagementData.quanity)
        cy.wait(2000)
        batchObj.selectBatchTemplate(batchManagementData.assignBatchTemplateName)
        cy.wait(1000)
        batchObj.selectCertificate(batchManagementData.assignCertificateName)
        cy.wait(1000)
        batchObj.clickOnScrollToAdditionalFiled()
        cy.wait(2000)
        batchObj.setLotNumber(batchManagementData.lotNumber)
        batchObj.setArticleNumber(batchManagementData.articleNumber)
        //createBatchObj.setDateOfManufacturing(batchManagementData.dateOfManufacturing)
        batchObj.setExpireMonth(batchManagementData.expireMonth)
        batchObj.setTokenInitiatorName(batchManagementData.tokenInitiatorName)
        batchObj.setUnitOfMeasurment(batchManagementData.unitOfMeasurment)
        cy.wait(1000)
        batchObj.setTokenPerUid(batchManagementData.tokenPerUid)
        batchObj.setTokenBufferAmount(batchManagementData.tokenBufferAmount)
        // createBatchObj.clickOnActivateWallet()
        // createBatchObj.clickOnSaveAsTemplate()
        batchObj.clickOnCreateBtn()
        batchObj.clickOnCreateSubmitBtn()
        cy.wait(2000)
        batchObj.downloadBatchInformation()
        cy.wait(5000)
    }) 

    it('TC_BATCH_TEMP_05: Verify that created batch template delete successfully.', () =>{
        cy.viewport(1440,900)
        loginObj.loginURL('/batch-management')
        cy.wait(3000)
        batchObj.clickOnbatchManagement()
        batchObj.clickOnBatchTemplate()
        cy.wait(1000)
        batchObj.clickOnBatchTemplateFilterMenu2()
        cy.wait(1000)
        batchObj.batchTemplateNameForSearch(batchManagementData.searchTemplateName)
        batchObj.createdPersonForSearch(batchManagementData.searchCreatedPerson)
        batchObj.clickOnApplyButton()
        cy.wait(1000)
        batchObj.clickOnkebabActionIcon()
        batchObj.clickDeleteTemplate()
        batchObj.clickOnConfirmDltTemp()
        cy.wait(2000)
    })

    it('TC_BATCH_06: Verify that the user is able to perform actions from the batch menu to update the assigning PWA.', () =>{
        cy.viewport(1440,900)
        loginObj.loginURL('/batch-management')
        cy.wait(3000)
        batchObj.clickOnbatchManagement()
        cy.wait(1000)
        batchObj.clickOnKebabMenuIcon()
        batchObj.clickOndeleteBatch()
        batchObj.clickOnCancelBtn()
        cy.wait(1000)
        
    })

    it('TC_PWA_07: Verify that unassign the PWA first before deleting the Batch', () =>{
        cy.viewport(1440,900)
        loginObj.loginURL('/pwa-management')
        cy.wait(3000)
        pwaObj.clickOnPWAManagement()
        cy.wait(2000)
        pwaObj.clickOnFilterList()
        pwaObj.setSearchByName(pwaManagementData.searchByName)
        pwaObj.selectOnStatus()
        pwaObj.clickOnapplyBtn()
        pwaObj.clickOnkebabMenuActionIcon()
        pwaObj.clickOnAssignBatch()
        cy.wait(1000)
        // Search batch template for assign if the batch doesn't exist before have unassigned
        pwaObj.clickOnUnassignBatch()
        pwaObj.clickOnunassignBatchConfirmBtn()
        cy.wait(1000)
        pwaObj.searchOnAssignBatch(pwaManagementData.searchAssignBatch)
        pwaObj.selectOnAssignBatch()
        cy.wait(1000)
        pwaObj.clickOnAssignBtn()
        cy.wait(1000)
        pwaObj.clickOnUnassignBatch()
        pwaObj.clickOnunassignBatchConfirmBtn()
        cy.wait(1000)

    })

    it('TC_BATCH_08: Verifies that the batch identified by the system is successfully deleted ', () =>{
        cy.viewport(1440,900)
        loginObj.loginURL('/batch-management')
        cy.wait(3000)
        batchObj.clickOnbatchManagement()
        batchObj.clickOnKebabMenuIcon()
        batchObj.clickOndeleteBatch()
        batchObj.clickOnConfirmTheDeleteBatch()
        cy.wait(1000)
    })
    
})


import { loginPage } from '../../pages/login/loginPage'
const loginObj = new loginPage()
import loginData from '../../fixtures/loginData.json'

import { batchManagementPage } from '../../pages/batchManagement/batchManagementPage'
const batchObj = new batchManagementPage()
import batchManagementData from '../../fixtures/batchManagementData.json'

import {pwaManagementPage } from '../../pages/pwaManagement/pwaManagementPage'
const pwaObj = new pwaManagementPage()
import pwaManagementData from '../../fixtures/pwaManagementData.json'