name: Login Test

on: push

jobs:
  login_test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Run Login Test
        uses: cypress-io/github-action@v6
        
